### ISSUE TITLE
Different results PLIER vs delayedPLIER

### ISSUE THREAD

**Issue by msubirana** [wgmao/DelayedPLIER#5]
Hi,

I ran `PLIER` and `delayedPLIER` using the same parameters and the same SVD (calculated using `BiocSingular::runRandomSVD()` ).

The mean correlation of both Z matrices is around 0.8, and the LVs look quite different across both models.

Is this expected? Am I missing any other parameters that could influence the different results? Do you have any suggestions on achieving the same results or ensuring that the functions generate sufficiently similar models?

Thanks for your feedback and help!

**Comment by wgmao** [comment]
Thank you for doing the benchmark work. Based on the formular, if the $Z$ is highly correlated, then $B$ should be consistent. Could you provide a little more details on the parameters? For both `PLIER` and `delayedPLIER`, are the `L1`, `L2` and `L4` close enough?

**Comment by msubirana** [comment]
Yes is based on `Z` matrix.

Here the output for `PLIER`:

```
k is set to 1042

Removing 4 pathways with too few genes

[1] 55.53993
[1] "L2 is set to 55.5399316449024"
[1] "L1 is set to 27.7699658224512"
errorY (SVD based:best possible) = 0.6327

New L3 is 0.000911881965554516

New L3 is 0.000804733010124613

New L3 is 0.000710174388842549

New L3 is 0.000804733010124613

New L3 is 0.000804733010124613

New L3 is 0.000911881965554516

New L3 is 0.000911881965554516

New L3 is 0.000911881965554516

New L3 is 0.000911881965554516

New L3 is 0.000911881965554516

New L3 is 0.000911881965554516

New L3 is 0.00103329763864764

New L3 is 0.000911881965554516

New L3 is 0.00103329763864764

Bdiff is not decreasing

Bdiff is not decreasing

Bdiff is not decreasing

New L3 is 0.000911881965554516

Bdiff is not decreasing

Bdiff is not decreasing

Bdiff is not decreasing

converged at  iteration 302 Bdiff is not decreasing

There are 216  LVs with AUC>0.70
```

And here `delayedPLIER`:


```
k is set to 1042

Removing 4 pathways with too few genes

[1] 55.53993
[1] "L2 is set to 55.5399316449024"
[1] "L1 is set to 27.7699658224512"
errorY (SVD based:best possible) = 0.6327

New L3 is 0.000911881965554516

New L3 is 0.000804733010124613

New L3 is 0.000710174388842549

New L3 is 0.000804733010124613

New L3 is 0.000804733010124613

New L3 is 0.000911881965554516

New L3 is 0.000911881965554516

New L3 is 0.000911881965554516

New L3 is 0.000911881965554516

New L3 is 0.000911881965554516

New L3 is 0.000911881965554516

New L3 is 0.00103329763864764

New L3 is 0.000911881965554516

New L3 is 0.00103329763864764

Bdiff is not decreasing

Bdiff is not decreasing

Bdiff is not decreasing
```

`L` are close enough but the resulting LVs are quite different. Do you have any ideas on how to achieve the same result, compare the models (using other approaches,) or determine if the models are actually similar enough?

**Comment by wgmao** [comment]
Sorry about the late reply. The logs look identical, but I am not sure if this is complete log for `DelayedPLIER`. By design, the last message should be about the number of LVs with AUC>0.70. Could you help check if any message is missing from the log?

**Comment by msubirana** [comment]
Hi again,

`DelayedPLIER` didn't generate any log of LV with an AUC > 0.70. I checked and found that there are 294 LVs with an AUC > 0.70.

**Comment by wgmao** [comment]
Thank you for the confirmation. Based on the logs, it seems `delayedPLIER` stops in the middle with fewer iterations compared with `PLIER`. You can modify your own branch to print out more detailed information to debug, e.g., the exact number of iterations. I would suggest a small-scale experiment by setting `max.iter=30` for both `PLIER` and `delayedPLIER`, and the output should be identical if they work as expected.

**Comment by msubirana** [comment]
Perfect, thanks!
