### ISSUE TITLE
delayedPLIER parallelization

### ISSUE THREAD

**Issue by msubirana** [wgmao/DelayedPLIER#6]
Hi,

Is it possible to `DelayedPLIER` parallelization?

**Comment by wgmao** [comment]
Currently `DelayedPLIER` is not in active development. It is possible to have an online learning version which will be more efficient, but the hyper parameters need to set in a different way to achieve identical or highly correlated output.

**Comment by msubirana** [comment]
Ok! Thanks for the answer!
